### ISSUE TITLE
New v1.7.2 does not see PIV-D certs on Yubikey

### ISSUE THREAD

**Issue by delfuego** [Yubico/yubioath-ios#120]
Now that #114 is fixed, plugging in our PIV-D-provisioned Yubikey 5Ci devices into our phones doesn't cause an app crash when we go to Configuration > Smart card extension — so that's a win! But unfortunately, the app doesn't appear to see our certs at all; when going to Configuration > Smart card extension, the app reports "No certificates on Yubikey". (See screenshot that I'm attaching.)

How can we help you debug this? The devices work perfectly to allow login to Windows and macOS computers, so the certs themselves are fine, and their provisioning onto the keys is such that both Windows and macOS happily see them.

![IMG_51922D42D88E-1](https://user-images.githubusercontent.com/550511/235212753-6fe50099-cfaf-4c08-aeaf-f3c7f378aa98.jpeg)

**Comment by jensutbult** [comment]
Thats unfortunate. The only reason I can see is that either we fail parsing out the raw data for the cert that the YubiKey returns or iOS fails to create a `SecCertificateRef` from the data. Is there a way I can get hold of a sample cert to test with?

**Comment by delfuego** [comment]
What's the right way to get you what you need? Getting a cert from the key is easy, so I could send you the cert from 9a (which I presume is the relevant one, since it's the one that'd be used for any website authentication); twocanoes' [Smart Card Utility](https://twocanoes.com/products/mac/smart-card-utility/) happily sees the certs on the key and lets me export them for example. But I don't know how to get you anything meaningful that allows you to test how Yubico Authenticator is able to actually read the key in the first place — is there any debug logging or other forensic data that we can gather at our end?

**Comment by jensutbult** [comment]
I think emailing me an exported cert would be a good start. You can send it to jens.utbult@yubico.com.
