### ISSUE TITLE
Does not support Steam code

### ISSUE THREAD

**Issue by dingwen07** [Yubico/yubioath-ios#97]
Steam code that is supported in Yubico Authenticator desktop app won't work in the iOS app and displayed as six digits code.

![image](https://user-images.githubusercontent.com/29778171/179400844-30e131a9-e23f-4aca-8dda-a8ad3ebc4059.png)

![image](https://user-images.githubusercontent.com/29778171/179400853-acd2dcf8-64ea-40ef-acf8-254f0822397b.png)

**Comment by jensutbult** [comment]
This looks like an old version of the Authenticator application. Can you reproduce the error in the latest version?

**Comment by dingwen07** [comment]
> This looks like an old version of the Authenticator application. Can you reproduce the error in the latest version?

The latest version of Yubico Authenticator desktop supported Steam code:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/29778171/189128798-84a44b5e-1f67-4c19-8036-76654b216125.png">

but the iOS version (latest from App Store) not:

![IMG_2442](https://user-images.githubusercontent.com/29778171/189129115-5c07cf66-20e4-4a68-9509-4eea90f7d295.PNG)

Here is the discussion thread of the Steam code for Yubico Authenticator desktop: https://github.com/Yubico/yubioath-desktop/issues/72, probably bly also this thread: https://github.com/Yubico/yubioath-desktop/issues/703

**Comment by jensutbult** [comment]
Thanks for the rapid reply! I can't reproduce the bug. Maybe you've got some special character in your account name? Could you provide a step-by-step instruction on how to create an account that returns a non functioning steam code?

**Comment by dingwen07** [comment]
> Thanks for the rapid reply! I can't reproduce the bug. Maybe you've got some special character in your account name? Could you provide a step-by-step instruction on how to create an account that returns a non functioning steam code?

Steps to reproduce:

- Open Yubico Authenticator desktop, add account
- Issuer: `Steam`; Account name: `my account name`; Secret key: `secret key`
- Click add
- Find the Steam account that just added, touch YubiKey
- Observe that Yubico Authenticator desktop generates a correct Steam code 
- Open Yubico Authenticator iOS, pull down to initiate NFC
- Observe that Yubico Authenticator iOS generates a TOTP code (6 digits) instead of Steam code

**Comment by jensutbult** [comment]
Thanks! I got it figured out. It only happens to accounts that requires touch and if you at the same time enable the "Bypass touch requirement" in the NFC Settings in the iOS app. We will fix this in the next release. While waiting for the release you could either add the Steam account without enabling the touch requirement or turn off the "Bypass touch requirement" setting in the app.
